// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package api;

public interface AreaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.AreaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double radius = 1;</code>
   * @return The radius.
   */
  double getRadius();
}
