// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package api;

public interface AreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.AreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double area = 1;</code>
   * @return The area.
   */
  double getArea();
}
