// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package api;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_AreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_AreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_AreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_AreaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SqrRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SqrRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SqrResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SqrResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\003api\"\035\n\013AreaRequest\022\016\n\006" +
      "radius\030\001 \001(\001\"\034\n\014AreaResponse\022\014\n\004area\030\001 \001" +
      "(\001\"\033\n\nSqrRequest\022\r\n\005value\030\001 \001(\001\"\035\n\013SqrRe" +
      "sponse\022\016\n\006result\030\001 \001(\00127\n\006Circle\022-\n\004Area" +
      "\022\020.api.AreaRequest\032\021.api.AreaResponse\"\0002" +
      "2\n\004Math\022*\n\003Sqr\022\017.api.SqrRequest\032\020.api.Sq" +
      "rResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_AreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_AreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_AreaRequest_descriptor,
        new java.lang.String[] { "Radius", });
    internal_static_api_AreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_AreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_AreaResponse_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_api_SqrRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_SqrRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SqrRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_api_SqrResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_SqrResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SqrResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
