// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package api;

public interface SqrResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SqrResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   * @return The result.
   */
  double getResult();
}
