// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package api;

public interface SqrRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SqrRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();
}
